### ISSUE TITLE
Mathematical extensions are not working and test suite does not detect it

### ISSUE THREAD

**Issue by jradek** [asciidoctor/docker-asciidoctor#116]
Hi,

I ran the test suite and all 24 test were reported as **passed*
```
$ make test
bats /Users/jradek/tmp/playground/docker-asciidoctor/tests/*.bats
...
✓ We can generate an HTML document with asciidoctor-mathematical as backend
...
✓ We can generate a PDF document with asciidoctor-mathematical as backend
...

24 tests, 0 failures
```

However, when a start a container and manually run the tested commands, especially the ones including the mathematical backend, none of them is working and no output is produced. 

E.g. the test for **HTML**:
```
bash-4.4# asciidoctor -D tests/tmp -r asciidoctor-mathematical tests/fixtures/sample-with-latex-math.adoc
asciidoctor: FAILED: /documents/tests/fixtures/sample-with-latex-math.adoc: Failed to load AsciiDoc document - can't modify frozen String (FrozenError)
  Use --trace for backtrace
```
Running with `--trace` yields:
```
bash-4.4# asciidoctor --trace -D tests/tmp -r asciidoctor-mathematical tests/fixtures/sample-with-latex-math.adoc
Traceback (most recent call last):
        20: from /usr/bin/asciidoctor:23:in `<main>'
        19: from /usr/bin/asciidoctor:23:in `load'
        18: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/bin/asciidoctor:15:in `<top (required)>'
        17: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
        16: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
        15: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
        14: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
        13: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
        12: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
        11: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:78:in `convert'
        10: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/load.rb:83:in `load'
         9: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:555:in `parse'
         8: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:555:in `each'
         7: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:556:in `block in parse'
         6: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:556:in `[]'
         5: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-mathematical-0.3.0/lib/asciidoctor-mathematical/extension.rb:40:in `process'
         4: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-mathematical-0.3.0/lib/asciidoctor-mathematical/extension.rb:40:in `each'
         3: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-mathematical-0.3.0/lib/asciidoctor-mathematical/extension.rb:41:in `block in process'
         2: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-mathematical-0.3.0/lib/asciidoctor-mathematical/extension.rb:100:in `handle_prose_block'
         1: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-mathematical-0.3.0/lib/asciidoctor-mathematical/extension.rb:135:in `handle_inline_stem'
/usr/lib/ruby/gems/2.5.0/gems/asciidoctor-mathematical-0.3.0/lib/asciidoctor-mathematical/extension.rb:135:in `gsub!': asciidoctor: FAILED: /documents/tests/fixtures/sample-with-latex-math.adoc: Failed to load AsciiDoc document - can't modify frozen String (FrozenError)
```

Similarly for **PDF**:
```
bash-4.4# asciidoctor-pdf -D tests/tmp -r asciidoctor-mathematical tests/fixtures/sample-with-latex-math.adoc
asciidoctor: FAILED: /documents/tests/fixtures/sample-with-latex-math.adoc: Failed to load AsciiDoc document - can't modify frozen String (FrozenError)
  Use --trace for backtrace
```
The trace is the same as for HTML.

Thx, JR

**Comment by dduportal** [comment]
Hi @jradek , when you "manually" run the test commands, which docker image are you using?

For information, we had an issue since some weeks, where the Docker Hub image for asciidoctor was not able to be built due to Github authorization issues. It means that the state of the `master` branch in this repository was different that the latest `asciidoctor/docker-asciidoctor` image. See https://github.com/asciidoctor/docker-asciidoctor/issues/115#issuecomment-557003234 for more information.


I just tried with the freshly built (1 hour ago) image that should have the latest changes, and it works:

```bash
$ docker pull asciidoctor/docker-asciidoctor
Using default tag: latest
latest: Pulling from asciidoctor/docker-asciidoctor
89d9c30c1d48: Already exists 
76434bd719a2: Pull complete 
e1bab9e0dee8: Pull complete 
2a42d81e75b3: Pull complete 
92642922b6d9: Pull complete 
Digest: sha256:eb60a6a96c34498387cc75f615e8032e2f8cbc7a9310589880d772d90a12cacf
Status: Downloaded newer image for asciidoctor/docker-asciidoctor:latest
docker.io/asciidoctor/docker-asciidoctor:latest

$ pwd
<redacted>/docker-asciidoctor/tests/fixtures

$ docker run --rm -ti -v $(pwd):/documents asciidoctor/docker-asciidoctor
bash-5.0# mkdir tmp
bash-5.0# asciidoctor -D /documents/tmp/ -r asciidoctor-mathematical /documents/sample-with-latex-math.adoc
bash-5.0#
```

Can you confirm it is the same on your side, using the latest image (tip: it has bash 5.0 inside, as part of Alpine Linux 3.10).

**Comment by jradek** [comment]
Hi,

thx for the info. Using the latest image, I can confirm everything works as expected. Sorry for my mistake not using it in the first place.

Keep up the good work,
JR

**Comment by dduportal** [comment]
Don't worry, the only reason why it works is because @mojavelinux was able to fix the build problem, so your issue was valid 10 hours ago :)
