### ISSUE TITLE
asciidoctor-diagram version 2.0.5

### ISSUE THREAD

**Issue by jtama-op** [asciidoctor/docker-asciidoctor#167]
Could it be possible to bump the asciidoctor-diagram version used.

I tried bebuilding the image with asciidcotor-diagram v2.0.5, but using it fails with the following error : 
```bash
Traceback (most recent call last):
        8: from /usr/bin/asciidoctor-pdf:23:in `<main>'
        7: from /usr/bin/asciidoctor-pdf:23:in `load'
        6: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.3/bin/asciidoctor-pdf:21:in `<top (required)>'
        5: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:274:in `parse!'
        4: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:274:in `each'
        3: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:276:in `block in parse!'
        2: from /usr/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- asciidoctor-diagram (LoadError)
        21: from /usr/bin/asciidoctor-pdf:23:in `<main>'
        20: from /usr/bin/asciidoctor-pdf:23:in `load'
        19: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.3/bin/asciidoctor-pdf:21:in `<top (required)>'
        18: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:274:in `parse!'
        17: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:274:in `each'
        16: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/options.rb:276:in `block in parse!'
        15: from /usr/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        14: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        13: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        12: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        11: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram.rb:1:in `<top (required)>'
        10: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram.rb:1:in `require_relative'
         9: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram/a2s.rb:2:in `<top (required)>'
         8: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram/a2s.rb:2:in `require_relative'
         7: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram/a2s/extension.rb:2:in `<top (required)>'
         6: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram/a2s/extension.rb:2:in `require_relative'
         5: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram/diagram_processor.rb:14:in `<top (required)>'
         4: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram/diagram_processor.rb:14:in `require_relative'
         3: from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-diagram-2.0.4/lib/asciidoctor-diagram/util/svg.rb:3:in `<top (required)>'
         2: from /usr/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
         1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- bigdecimal (LoadError)
```

Many standard libraries have been added to plantuml which allow much more graphic diagrams.

**Comment by jtama-op** [comment]
Working with ruby-bigdecimal added to required dependencies.

**Comment by mojavelinux** [comment]
If you upgrade to asciidoctor-diagram 2.0.5 instead, you don't need bigdecimal. asciidoctor-diagram was incorrectly requiring it, but that has been fixed now. See https://github.com/asciidoctor/asciidoctor-diagram/issues/313

**Comment by mojavelinux** [comment]
> I tried bebuilding the image with asciidcotor-diagram v2.0.5, but using it fails with the following error 

you didn't update something correctly, because the error message indicates 2.0.4 is still being used.

**Comment by jtama-op** [comment]
Indeed though I tried again today and I stil needed ruby-bigdecimal dep.

**Comment by mojavelinux** [comment]
Giving this more thought, bigdecimal is part of the stdlib of Ruby, so it
should be included anyway or the Ruby installation is incomplete. So I'm in
favor of adding it on principal.

**Comment by jtama-op** [comment]
Yes and from what I see we should just wait for 2.0.6 which solves the issue

**Comment by dduportal** [comment]
Hello @jtama-op , it has been bumped to the version `2.1.0` in the image's release `1.3.0` (https://github.com/asciidoctor/docker-asciidoctor/releases/tag/1.3.0), and the latest release of the image (`1.3.3` https://github.com/asciidoctor/docker-asciidoctor/releases/tag/1.3.3 is using the native `ruby-bigdecimal` package. Closing the issue, but please feel free to reopen it with a comment if the latest `1.3.3` image is not working as expected.

Thanks a lot for reporting!
