### ISSUE TITLE
asciidoctor-confluence -v command 'tried to create Proc object without a block'

### ISSUE THREAD

**Issue by ParHandler** [asciidoctor/docker-asciidoctor#315]
I have the problem on my Alpine Linux 3.16.3.
Installation via gem install asciidoctor-confluence.

Ruby version info: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-musl]

Command
```bash
/documents/docs # asciidoctor-confluence -v
```
throws exception

```bash
/usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday/options.rb:153:in `new': tried to create Proc object without a block (ArgumentError)
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday/options.rb:153:in `memoized'
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday/options.rb:234:in `<class:ProxyOptions>'
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday/options.rb:216:in `<module:Faraday>'
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday/options.rb:1:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday.rb:80:in `block in require_libs'
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday.rb:79:in `each'
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday.rb:79:in `require_libs'
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday.rb:240:in `<module:Faraday>'
        from /usr/lib/ruby/gems/3.1.0/gems/faraday-0.9.2/lib/faraday.rb:16:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence.rb:6:in `<top (required)>'
        from /usr/lib/ruby/gems/3.1.0/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence/options.rb:2:in `require_relative'
        from /usr/lib/ruby/gems/3.1.0/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence/options.rb:2:in `<top (required)>'
        from /usr/lib/ruby/gems/3.1.0/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence/invoker.rb:4:in `require_relative'
        from /usr/lib/ruby/gems/3.1.0/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence/invoker.rb:4:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/asciidoctor-confluence-0.0.2/bin/asciidoctor-confluence:4:in `<top (required)>'
        from /usr/bin/asciidoctor-confluence:25:in `load'
        from /usr/bin/asciidoctor-confluence:25:in `<main>'
```
asciidoctor-confluence 0.0.2 doesn't work properly

See https://github.com/asciidoctor/asciidoctor-confluence/issues/32

**Comment by dduportal** [comment]
Thanks for opening this issue @ParHandler .

Given https://github.com/asciidoctor/asciidoctor-confluence/issues/32, it sounds like this tools should be removed from the Docker image as it is not usable (and not given attention).

Ping @mojavelinux do you concur?

**Comment by barthel** [comment]
See the comment of @mojavelinux (https://github.com/asciidoctor/asciidoctor-confluence/issues/29#issuecomment-1515804101)

> Consider this an official call for maintainer. If no one follows up in the next few days, I'll assume there is no one interested and will archive it.

Version 1.50.0 could be a good candidate to remove `asciidoctor-confluence` from Docker image.

**Comment by dduportal** [comment]
> See the comment of @mojavelinux ([asciidoctor/asciidoctor-confluence#29 (comment)](https://github.com/asciidoctor/asciidoctor-confluence/issues/29#issuecomment-1515804101))
> 
> > Consider this an official call for maintainer. If no one follows up in the next few days, I'll assume there is no one interested and will archive it.
> 
> Version 1.50.0 could be a good candidate to remove `asciidoctor-confluence` from Docker image.

Good idea, thanks for the reminder!

Are you willing to send a PR or do you want me to take care of it?

Btw, I would bump the version to 2.0.0. As per https://semver.org/, this change (removal of `asciidoctor-confluence`) remove an element from the contract with end user, so it should be a major increment (unless I missed something)

**Comment by snowe2010** [comment]
Agh, I just started looking into this repo yesterday and would love to maintain it to avoid it being removed!
