### ISSUE TITLE
Asciidoctor-revealjs is not working with the last version of the image (05 january 2017)

### ISSUE THREAD

**Issue by dduportal** [asciidoctor/docker-asciidoctor#64]
When calling `asciidoctor-revealjs` you got this error:

```
docker run --rm -t --entrypoint asciidoctor-revealjs asciidoctor/docker-asciidoctor --version
/usr/lib/ruby/gems/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs.rb:5:in `require_relative': cannot load such file -- /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs/converter (LoadError)
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs.rb:5:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-revealjs-1.1.0/bin/asciidoctor-revealjs:4:in `<top (required)>'
	from /usr/bin/asciidoctor-revealjs:23:in `load'
	from /usr/bin/asciidoctor-revealjs:23:in `<main>'
```

**Comment by dduportal** [comment]
Looks like related to asciidoctor-revealjs 1.1.0 version: https://github.com/asciidoctor/asciidoctor-reveal.js/issues/172

**Comment by dduportal** [comment]
Looks like the version `1.1.1` had been released in the meantime.
Any merged pull requests that will trigger a rebuild will fix this on the "latest" image.


For any user landing here before this is closed, the short term fix is to update the gem asciidoctor-revealjs on your images:

* Command to run inside the current container/image:
```
gem update --no-document asciidoctor-revealjs
```

* Runtime example:
```
docker run --rm -ti --entrypoint bash asciidoctor/docker-asciidoctor
bash-4.3# asciidoctor-revealjs -v
/usr/lib/ruby/gems/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs.rb:5:in `require_relative': cannot load such file -- /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs/converter (LoadError)
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs.rb:5:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-revealjs-1.1.0/bin/asciidoctor-revealjs:4:in `<top (required)>'
	from /usr/bin/asciidoctor-revealjs:23:in `load'
	from /usr/bin/asciidoctor-revealjs:23:in `<main>'
bash-4.3# gem update --no-document asciidoctor-revealjs
Updating installed gems
Updating asciidoctor-revealjs
Fetching: asciidoctor-revealjs-1.1.1.gem (100%)
Successfully installed asciidoctor-revealjs-1.1.1
Gems updated: asciidoctor-revealjs
bash-4.3# asciidoctor-revealjs -v
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

* Build time (with a `Dockerfile`) example:
```
FROM asciidoctor/docker-asciidoctor
RUN gem update --no-document asciidoctor-revealjs
...
```
