### ISSUE TITLE
Unable to generate PDF if pygments is chosen as the source highlighter.

### ISSUE THREAD

**Issue by Muzamri** [asciidoctor/docker-asciidoctor#68]
Hello,

I am unable to generate a PDF with the following content:
```
= Test
:source-highlighter: pygments

[source,java]
----
public static void main(String [] args){

}
----

[source,sh]
----
$ du -sh
----

```

The error message that I am getting:
```
bash-4.3# asciidoctor-pdf --trace index.adoc
/usr/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/formatted_text/formatter.rb:16:in `format': undefined method `match' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:1324:in `convert_listing_or_literal'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118:in `convert'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:70:in `convert'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `block in content'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `map'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `content'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1120:in `content'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:134:in `convert_content_for_block'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:207:in `convert_document'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118:in `convert'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1060:in `convert'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1502:in `convert'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `block in convert_file'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `open'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `convert_file'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:108:in `block in invoke!'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `invoke!'
	from /usr/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /usr/bin/asciidoctor-pdf:23:in `load'
	from /usr/bin/asciidoctor-pdf:23:in `<main>'
```

But if I were to change the highlighter to `:source-highlighter: coderay`, the PDF would be generated just fine.

To start the container, I'm using a script:
```sh
#!/usr/bin/env bash

docker \
    run \
    -it \
    --rm \
    -v $(pwd)/documents:/documents/ \
    asciidoctor/docker-asciidoctor:latest
```

My working directory:
```sh
error-report/
├── documents
│   └── index.adoc
└── start-container.sh

1 directory, 2 files
```

Docker image being used:
```sh
$ docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
asciidoctor/docker-asciidoctor   latest              8281da120098        4 weeks ago         449MB
```

Local Gems:
```sh
bash-4.3# gem list

*** LOCAL GEMS ***

addressable (2.5.2)
afm (0.2.2)
Ascii85 (1.0.2)
asciidoctor (1.5.6.1)
asciidoctor-confluence (0.0.2)
asciidoctor-diagram (1.5.7)
asciidoctor-epub3 (1.5.0.alpha.7)
asciidoctor-mathematical (0.2.2)
asciidoctor-pdf (1.5.0.alpha.16)
asciidoctor-revealjs (1.1.1)
coderay (1.1.2)
concurrent-ruby (1.0.5)
css_parser (1.6.0)
epubcheck (3.0.1)
faraday (0.9.2)
gepub (0.6.9.2)
haml (5.0.4)
hashery (2.1.2)
i18n (0.9.1)
json (default: 2.0.4, 1.8.6)
kindlegen (3.0.3)
mathematical (1.6.8)
mini_portile2 (2.1.0)
multi_json (1.12.1)
multipart-post (2.0.0)
nokogiri (1.6.8.1)
openssl (default: 2.0.5)
pdf-core (0.7.0)
pdf-reader (2.0.0)
polyglot (0.3.5)
prawn (2.2.2)
prawn-icon (1.3.0)
prawn-svg (0.27.1)
prawn-table (0.2.2)
prawn-templates (0.1.1)
psych (default: 2.2.2)
public_suffix (3.0.1)
pygments.rb (1.1.2)
rake (12.3.0)
rouge (3.1.0)
ruby-enum (0.7.2)
ruby-rc4 (0.1.5)
rubyzip (1.2.1)
safe_yaml (1.0.4)
slim (3.0.9)
temple (0.8.0)
thread_safe (0.3.6)
tilt (2.0.8)
treetop (1.5.3)
ttfunk (1.5.1)
```

PS: I was actually using the previous `:latest` version of this docker image and it was working fine (with pygments) till today -- I don't know when it / what happened that caused it to suddenly stopped working. Upgrading to the current `:latest` version didn't help.

Previous Image ID (afaict):
```sh
REPOSITORY                       TAG                 IMAGE ID            CREATED              SIZE
asciidoctor/docker-asciidoctor   <none>              212019b2d6ef        2 months ago         441MB
```

Thank you.

**Comment by mojavelinux** [comment]
This looks like the same issue as https://github.com/asciidoctor/asciidoctor/issues/2341 and https://github.com/asciidoctor/asciidoctor-epub3/issues/156. Basically, the pygments library sometimes fails and silently returns nil. We have to deal with that.

This is actually an issue in Asciidoctor PDF. Can you open the same issue there? Then I'll address it.

Until it's fixed, I strongly encourage you to use rouge instead of pygments.

**Comment by Muzamri** [comment]
Hi @mojavelinux,

Apologies for the late response, I've cross-posted the issue to [Asciidoctor PDF](https://github.com/asciidoctor/asciidoctor-pdf/issues/884) as requested.

Thank you.

**Comment by mojavelinux** [comment]
Thanks!

**Comment by mojavelinux** [comment]
While I understand that this can fail if Pygments doesn't return a value, when I try this with the Docker container it never fails. Are you sure this happens every time?

**Comment by Muzamri** [comment]
Hi,

I can't get it to give me the reported error when I tried it today as well (not even once).

But as I mentioned previously:
``PS: I was actually using the previous :latest version of this docker image and it was working fine (with pygments) till today -- I don't know when it / what happened that caused it to suddenly stopped working. Upgrading to the current :latest version didn't help.``

Closing this issue is an option -- as I am not sure if there is a reliable way to trigger the error.

**Comment by mojavelinux** [comment]
Let's close this issue then and reopen if it comes back. We'll be ready for it ;)

**Comment by mojavelinux** [comment]
Btw, I'm still proceeding with the fallback behavior so it doesn't cause the processor to fail when it does happen.

**Comment by Muzamri** [comment]
Sounds good to me 😃 - thank you again for your time.
